"""empty message

Revision ID: 0f9da8572da0
Revises: 8317621a3c58
Create Date: 2024-08-25 00:59:58.866594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9da8572da0'
down_revision = '8317621a3c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_flights')
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.alter_column('flight_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('flight_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('cost')

    op.create_table('_alembic_tmp_flights',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('flight_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('destination', sa.VARCHAR(length=120), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
