"""Add origin to Flight

Revision ID: 9d951fe72cb3
Revises: 0f9da8572da0
Create Date: 2024-08-25 01:30:54.938310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d951fe72cb3'
down_revision = '0f9da8572da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.alter_column('flight_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.alter_column('flight_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
